#!/bin/bash -
TOPDIR=$(pwd | awk -F '/3' '{print $1}')

IFS=$'\r\n' GLOBIGNORE='*' command eval  'XYZ=($(cat ServerIPNodeID))'
IFS=$',' GLOBIGNORE='*' command eval  'NodesID=($(echo "${XYZ[1]}"))'
for j in $(seq 2 ${#NodesID[@]})
  do
  	nodeid="${NodesID[j-1]}"
    MyFile=routing$nodeid.conf

    PREFIX=$(printf "%s" "$TOPDIR" | sed 's/\//\\\//g')
    sed -i -e 's/@TOPDIR@/'"${PREFIX}/" ${MyFile}

    sed -i -e 's/@NODEID@/'"${nodeid}/g" ${MyFile}

done

scripts/docker-democtl-host start "$@" "$TOPDIR" "3"
scripts/docker-rtctl-host start "$@" "$TOPDIR" "3"
