#!/bin/bash -
PREFIX=$(pwd | awk -F '/3' '{print $1}')

numofcontainers=3

for (( i=1; i<=$numofcontainers; i++ ))
do
	cp routing.EXAMPLE routing$i.conf
	MyFile=routing$i.conf

	PREFIXA=$(pwd)
	PREFIXB=$(printf "%s" "$PREFIXA" | sed 's/\//\\\//g')
	sed -i -e 's/@PREFIX@/'"${PREFIXB}/" ${MyFile}

	newline="$i"
	sed -i -e 's/@ID@/'"${newline}/g" ${MyFile}
done

scripts/docker-democtl-host start "$@" "$PREFIX" 3 $numofcontainers
scripts/docker-rtctl-host start "$@" "$PREFIX" 3 $numofcontainers