#!/bin/bash -
#
# Copyright (c) 2014-2016 - Adjacent Link LLC, Bridgewater, New Jersey
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# * Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in
#   the documentation and/or other materials provided with the
#   distribution.
# * Neither the name of Adjacent Link LLC nor the names of its
#   contributors may be used to endorse or promote products derived
#   from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

prefix=rt-
routerbridgeprefix=rt-bridge-
bridge=emanenode0
bridgecontrol=1
lxcmajorversion=

if (which lxc-version &> /dev/null); then
    lxcmajorversion=$(lxc-version | awk -F: '{print $2}' | awk -F. '{print $1}')
else
    lxcmajorversion=$(lxc-stop --version  | awk -F. '{print $1}')
fi

check_bridge()
{
    return $(brctl show | awk "/^$1[\t\s]+/{exit 1}")
}

check_euid()
{
    if [ $EUID -ne 0 ]
    then
        echo "You need to be root to perform this command."
        exit 1
    fi
}

start_emaneeventservice()
{
    local xml=$1
    local logfile=$2
    local pidfile=$3
    local uuidfile=$4
    local starttime="$5"

    local startoption=""

    if [ -n "$starttime" ]; then
        startoption="--starttime $(date --date "$starttime" "+%H:%M:%S")"
    fi

    if [ -f $xml ]; then

        echo "Starting emaneeventservice: $xml at $starttime"

        emaneeventservice -d "$xml" -l 3 -f "$logfile" \
                          --pidfile "$pidfile" --uuidfile "$uuidfile" \
                          $startoption

        retval=$?
    else

        echo "Missing emaneeventservice XML: $xml"

        retval=1
    fi

    return $retval
}

start_emane()
{
    local xml=$1
    local logfile=$2
    local pidfile=$3
    local uuidfile=$4

    if [ -f $xml ]; then

        echo "Starting emane: $xml"

        emane "$xml" -d -l 4 -f "$logfile" \
              --pidfile "$pidfile" --uuidfile "$uuidfile"

	echo "Please start emane in debugger: $xml"
        echo "command is: emane \"$xml\" -r -d -l 4 -f \"$logfile\" --pidfile \"$pidfile\" --uuidfile \"$uuidfile\""
        read hi
        #gnome-terminal -e "gdb -ex=r --args emane \"$xml\" -r -d -l 3 -f \"$logfile\" --pidfile \"$pidfile\" --uuidfile \"$uuidfile\""


        retval=$?
    else
        echo "Missing emane XML: $xml"
        retval=1
    fi

    return $retval
}

start_emanetransportd()
{
    local xml=$1
    local logfile=$2
    local pidfile=$3
    local uuidfile=$4

    if [ -f $xml ]; then

        echo "Starting emanetransport: $xml"

        emanetransportd -r -d "$xml" -l 3 -f "$logfile" \
                        --pidfile "$pidfile" --uuidfile "$uuidfile"

        retval=$?
    else

        echo "Missing emaneeventd XML: $xml"

        retval=1
    fi

    return $retval
}

start_otestpoint_broker()
{
    local xml=$1
    local logfile=$2
    local pidfile=$3
    local uuidfile=$4

    if [ -f $xml ]; then

        echo "Starting otestpoint-broker: $xml"

        otestpoint-broker "$xml" -d -l 3 -f "$logfile" \
                          --pidfile "$pidfile" --uuidfile "$uuidfile"

        retval=$?
    else
        echo "Missing otestpoint-broker XML: $xml"
        retval=1
    fi

    return $retval
}

wait_for_device()
{
    local device=$1
    local timeout=$2
    local waited=0

    echo -n "waiting for $device..."

    while(! ip link show | grep -q $device); do

        if [ $waited -lt $timeout ]; then
            sleep 1
            waited=$(($waited + 1))
        else
            echo "not found"
            return 1
        fi
    done

    echo "found"
    return 0
}

usage()
{
    echo
    echo " usage: democtl-host start [START OPTIONS]... TOPDIR DEMOID NUMBER_NODES"
    echo "        democtl-host stop  [STOP OPTIONS]... TOPDIR DEMOID NUMBER_NODES"
    echo "        democtl-host help"
    echo
    echo " start options:"
    echo "  -s STARTTIME  Demo scenario start time HH:MM:SS or any 'date' command"
    echo "                 syntax (i.e. 'now + 30 sec')"
    echo "  -e ENVFILE    Environment file to source"
    echo "  -n            Do not control the bridge"
    echo
    echo " stop options:"
    echo "  -e ENVFILE    Environment file to source"
    echo "  -n            Do not control the bridge"
    echo
}

if [ $EUID -ne 0 ]
then
    echo "You need to be root to perform this command."
    exit 1
fi

case "$1" in
    start)
        starttime=
        envcommand=

        OPTIND=2

        # process options
        while getopts ":s:e:n" opt; do
            case $opt in
                n)
                    bridgecontrol=0
                    ;;
                s)
                    echo "starttime=$OPTARG"
                    starttime="$OPTARG"
                    ;;
                e)
                    envcommand="-e $OPTARG"
                    . "$OPTARG"
                    ;;
                \?)
                    echo "Invalid option: -$OPTARG" >&2
                    exit 1
                    ;;
            esac
        done

        shift $((OPTIND - 1))

        if [ $# -ne 3 ]
        then
            echo "Invalid number of parameters $@" >&2
            exit 1
        fi

        shopt -s extglob
        topdir=$1
        demoid=$2
        nodecount=$3

        if [[ $demoid != +([0-9]) ]]
        then
            echo "Invalid demo id: $demoid" >&2
            exit 1
        fi

        if [[ $nodecount != +([0-9]) ]]
        then
            echo "Invalid node count: nodecount" >&2
            exit 1
        fi

        if [ -z "$starttime" ]
        then
            starttime=$(date -R --date "now + 40 sec")
        else
            starttime=$(date --date "$starttime" "+%H:%M:%S")
        fi

        utctime=$(date -R --date="$starttime" --utc)

        if [ ! -d $nodevolume ]
        then
            echo "Node volume does not exist:  $nodevolume" >&2
            exit 1
        fi


        mkdir -p persist/host/var/log
        mkdir -p persist/host/var/run

        if [ -n "$SUDO_USER" ]
        then
            chown -R $SUDO_USER:`id -gn $SUDO_USER` persist
        fi

        if [ -f  /var/run/demo-rt.lock ]
        then
            echo "Demo example $(cat /var/run/demo-rt.lock) already running" >&2
            echo "Run './demo-stop' first" >&2
            exit 1
        else
            echo $demoid >  /var/run/demo-rt.lock
        fi

        if [[ $bridgecontrol -ne 0 ]]
        then
            if (check_bridge $bridge)
            then
                echo "Creating bridge: $bridge"

		docker network create --driver=bridge --subnet=10.99.0.100/24 --ip-range=10.99.0.100/24 --gateway=10.99.0.100 --attachable --opt "com.docker.network.bridge.name"="$bridge" $bridge

                #brctl addbr $bridge

                wait_for_device $bridge 10

                ip link set $bridge up

                sleep 1

                ip addr add 10.99.0.100/24 dev $bridge

                iptables -I INPUT -i $bridge -j ACCEPT

                iptables -I FORWARD -i $bridge -j ACCEPT

		echo "Done creating bridge: $bridge"
            else
                echo "Found bridge: $bridge"
            fi
        fi

        # disable realtime scheduling contraints
        sysctl kernel.sched_rt_runtime_us=-1

        for nodeid in $(seq 1 $nodecount)
        do
            mkdir -p persist/$nodeid/var/log
            mkdir -p persist/$nodeid/var/run
            rm -f persist/$nodeid/var/log/*
            rm -f persist/$nodeid/var/run/*

            if [ -n "$SUDO_USER" ]
            then
                chown -R $SUDO_USER:`id -gn $SUDO_USER` persist/$nodeid
            fi

            name=$prefix$nodeid
            hex=$(printf "%02x" $nodeid)
	    routerbridge=$routerbridgeprefix$nodeid


	    if (check_bridge $routerbridge)
            then
                echo "Creating bridge: $routerbridge"

		docker network create --driver=bridge --subnet=10.100.$nodeid.100/24 --ip-range=10.100.$nodeid.100/24 --gateway=10.100.$nodeid.100 --attachable --opt "com.docker.network.bridge.name"="$routerbridge" $routerbridge

                #brctl addbr $bridge

                wait_for_device $routerbridge 10

                ip link set $routerbridge up

                sleep 1

                ip addr add 10.100.$nodeid.100/24 dev $routerbridge

                iptables -I INPUT -i $routerbridge -j ACCEPT

                iptables -I FORWARD -i $routerbridge -j ACCEPT

		echo "Done creating bridge: $routerbridge"
            else
                echo "Found bridge: $routerbridge"
            fi


	    cat <<EOF > persist/$nodeid/var/run/docker.env.$nodeid
nodeid=$nodeid
topdir=$topdir/$demoid


EOF

            cat <<EOF > persist/$nodeid/var/run/docker.conf.$nodeid
--detach \
--tty \
--volume /home/user/emane-install/emane-dlep-tutorial:/home/user/emane-install/emane-dlep-tutorial \
--volume /home/user/emane-install/emane-dlep-tutorial/3/scripts:/home/user/emane-install/emane-dlep-tutorial/3/scripts \
--volume /home/user:/home/user \
--volume /usr:/usr \
--volume /sbin/iptables:/sbin/iptables \
--volume /etc:/etc \
--volume /bin:/bin \
--volume /lib:/lib \
--name=$name \
--hostname=$name \
--security-opt seccomp=unconfined \
--security-opt no-new-privileges:false \
--cap-add=ALL \
--privileged=true \
--env-file persist/$nodeid/var/run/docker.env.$nodeid \
--entrypoint /bin/bash \
simdoc \

EOF

#--entrypoint /home/user/emane-dlep-tutorial/scripts/demo-init \
# to connect to container sudo docker exec -i -t node-1 /bin/bash
# to run sim emane platform1.xml -l 4 -f log1.tmp
#--network=$bridge \
#--mac-address=02:00:$hex:01:00:01 \
#--ip=10.99.0.$nodeid \
            #if [[ $lxcmajorversion -ne 0 ]]
            #then
            #    echo "lxc.aa_profile = unconfined" >> persist/$nodeid/var/run/docker.conf.$nodeid
            #fi

            echo "Starting docker instance: $name"

            docker run $(cat "persist/$nodeid/var/run/docker.conf.$nodeid")

	    docker logs $name >& persist/$nodeid/var/log/docker-execute.log.$nodeid

	    docker network connect --ip 10.100.$nodeid.1 $routerbridge $name 

            while (! test -f persist/$nodeid/var/log/docker-execute.log.$nodeid)
            do
                sleep 1
            done

	    docker exec $name $PWD/scripts/docker-rtdemo-init &

        done

        if [ -f transportdaemon.xml ] &&
               [ ! -f NO-host-emanetransportd ]
        then

            start_emanetransportd \
                transportdaemon.xml \
                persist/host/var/log/transportdaemon.log \
                persist/host/var/run/transportdaemon.pid \
                persist/host/var/run/transportdaemon.uuid
        fi

        if [ -f platform.xml ] &&
               [ ! -f NO-host-emane ]
        then

            start_emane \
                platform.xml \
                persist/host/var/log/emane.log \
                persist/host/var/run/emane.pid \
                persist/host/var/run/emane.uuid
        fi

        if [ ! -f persist/host/var/run/emaneeventservice.pid ]
        then
            if [ -f eventservice.xml ] &&
                   [ ! -f NO-host-emaneeventservice ]
            then
                start_emaneeventservice eventservice.xml \
                                        persit/host/var/log/emaneeventservice.log \
                                        persist/host/var/run/emaneeventservice.pid \
                                        persist/host/var/run/emaneeventservice.uuid \
                                        "$starttime"
            fi
        else
            echo "Found an emaneeventservice pid file: unable to start" >&2
        fi

        if [ -f otestpoint-broker.xml ] &&
               [ ! -f NO-host-otestpoint-broker ]
        then
            start_otestpoint_broker \
                otestpoint-broker.xml \
                persist/host/var/log/otestpoint-broker.log \
                persist/host/var/run/otestpoint-broker.pid \
                persist/host/var/run/otestpoint-broker.uuid
        fi

        if [ -x host-poststart ]
        then
            ./host-poststart $demoid $nodecount
        fi
        ;;

    stop)
        OPTIND=2

        # process options
        while getopts ":ne:" opt; do
            case $opt in
                n)
                    bridgecontrol=0
                    ;;
                e)
                    envcommand="-e $OPTARG"
                    . "$OPTARG"
                    ;;
                \?)
                    echo "Invalid option: -$OPTARG" >&2
                    exit 1
                    ;;
            esac
        done

        shift $((OPTIND - 1))

        if [ $# -ne 3 ]
        then
            echo "Invalid number of parameters" >&2
            exit 1
        fi

        shopt -s extglob
        topdir=$1
        demoid=$2
        nodecount=$3

        if [[ $demoid != +([0-9]) ]]
        then
            echo "Invalid demo id: $demoid" >&2
            exit 1
        fi

        if [[ $nodecount != +([0-9]) ]]
        then
            echo "Invalid node count: nodecount" >&2
            exit 1
        fi

        if [ ! -f  /var/run/demo-rt.lock ]
        then
            echo "There does not appear to be a running demo. No /var/run/demo-rt.lock present." >&2
            exit 1
        fi


        if [ -x ./host-prestop ]
        then
            #./host-prestop $demoid $nodecount !!!!!!!!!!!!!!!!
	    echo "host-prestop"
        fi

        for nodeid in $(seq 1 $nodecount)
        do
            echo "Stopping docker instance: $prefix$nodeid"

	    routerbridge=$routerbridgeprefix$nodeid

            if [[ $lxcmajorversion -ne 0 ]]
            then
                #lxc-stop -n $prefix$nodeid -k
		docker stop $prefix$nodeid 
		docker rm $prefix$nodeid
		    if (! check_bridge $routerbridge)
		    then
		        echo "Removing bridge: $routerbridge"

                iptables -D INPUT -i $routerbridge -j ACCEPT

                iptables -D FORWARD -i $routerbridge -j ACCEPT

		        ip link set $routerbridge down

			docker network rm $routerbridge

		        #brctl delbr $routerbridge

			echo "Done removing brifge: $routerbridge"
		    fi
            else
		    if (! check_bridge $routerbridge)
		    then
		        echo "Removing bridge: $routerbridge"

                iptables -D INPUT -i $routerbridge -j ACCEPT

                iptables -D FORWARD -i $routerbridge -j ACCEPT

		        ip link set $routerbridge down

			docker network rm $routerbridge

		        #brctl delbr $routerbridge

			echo "Done removing brifge: $routerbridge"
		    fi
		docker stop $prefix$nodeid
		docker rm $prefix$nodeid
                #lxc-stop -n $prefix$nodeid
            fi

        done

        if [ -f persist/host/var/run/otestpoint-broker.pid ]
        then
            kill -QUIT $(cat persist/host/var/run/otestpoint-broker.pid)
            rm -f persist/host/var/run/otestpoint-broker.pid
        fi

        if [ -f persist/host/var/run/emaneeventservice.pid ]
        then
            kill -QUIT $(cat persist/host/var/run/emaneeventservice.pid)
            rm -f persist/host/var/run/emaneeventservice.pid
        fi

        if [ -f persist/host/var/run/emane.pid ]
        then
            kill -QUIT $(cat persist/host/var/run/emane.pid)
            rm -f persist/host/var/run/emane.pid
        fi

        if [ -f persist/host/var/run/transportdaemon.pid ]
        then
            kill -QUIT $(cat persist/host/var/run/transportdaemon.pid)
            rm -f persist/host/var/run/transportdaemon.pid
        fi

        if [[ $bridgecontrol -ne 0 ]]
        then
            if (! check_bridge $bridge)
            then
                echo "Removing bridge: $bridge"
                iptables -D INPUT -i $bridge -j ACCEPT

                iptables -D FORWARD -i $bridge -j ACCEPT
                ip link set $bridge down

		docker network rm $bridge

                #brctl delbr $bridge


		echo "Done removing brifge: $bridge"
            fi
        fi

        sleep 2

        for vif in $(ip link show | awk -F : '/veth[0-9]+\.[0-9]/{gsub(/@if[0-9]+/,"",$2); print $2;}')
        do
            echo "Performing extra cleanup of vif $vif"
            ip link del dev $vif 2>&1 > /dev/null
        done

        # paranoia - make sure everything is down
        for i in $(ps ax | awk '/emaneeventservic[e] /{print $1}')
        do
            echo "Performing extra cleanup of emaneeventservice [$i]"
            kill -9 $i;
        done

        for i in $(ps ax | awk '/emanetransport[d] /{print $1}')
        do
            echo "Performing extra cleanup of emanetransportd [$i]"
            kill -9 $i;
        done

        for i in $(ps ax | awk '/eman[e] /{print $1}')
        do
            echo "Performing extra cleanup of emane [$i]"
            kill -9 $i;
        done

        if [ -x ./host-poststop ]
        then
            ./host-poststop $demoid $nodecount
        fi

	    rm -f /var/run/demo-rt.lock
        ;;

    help)
        usage
        exit 0
        ;;
    *)
        usage
	    exit 1
        ;;
esac
